export const GPT_LIST_SUCCESS = "GPT_LIST_SUCCESS";

export const CHAT_LIST_SUCCESS = "CHAT_LIST_SUCCESS";
export const CHAT_USECASE_SUCCESS = "CHAT_USECASE_SUCCESS";
export const CHAT_INPUT_SUCCESS = "CHAT_INPUT_SUCCESS";
