export const GET_SUCCESS_SHOW = 'GET_SUCCESS_SHOW';
export const GET_SUCCESS_HIDE = "GET_SUCCESS_HIDE";
export const GET_ALERT_SHOW = "GET_ALERT_SHOW";
export const GET_ALERT_HIDE = "GET_ALERT_HIDE";
export const GET_ERROR_SHOW = "GET_ERROR_SHOW";
export const GET_ERROR_HIDE = "GET_ERROR_HIDE";
export const GET_LOADING_SHOW = "GET_LOADING_SHOW";
export const GET_LOADING_HIDE = "GET_LOADING_HIDE";